SETUP__:
  sponsor: "ABC Pharma, Inc"
  projectnumber: "DEM104101F"
  data_path: data/derived
DEM104101F_PK:
  description: Population PK analysis data set
DEM104101F_PKPD:
  description: Population PK/PD analysis data set
DEM104101F_AE:
  description: AE analysis data set

